# Generated by Django 2.2.5 on 2019-09-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='useravatar.jpg', upload_to='profile/'),
        ),
    ]
