# Generated by Django 2.2.5 on 2019-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20190926_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Y_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('lien', models.URLField(max_length=300)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_upd', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Y_Video',
                'verbose_name_plural': 'Y_Videos',
            },
        ),
    ]
